services:
  postgres:
    image: postgres:15-alpine
    container_name: flexspace-postgres
    environment:
      POSTGRES_USER: flexspace
      POSTGRES_PASSWORD: flexspace_dev_password
      POSTGRES_DB: flexspace
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: ./backend
    container_name: flexspace-app
    env_file:
      - ./backend/.env
    environment:
      # Infos DB pour le Dockerfile safe
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_URL: postgres://flexspace:flexspace_dev_password@postgres:5432/flexspace
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:
